name: PHPStan Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  phpstan:
    name: Run PHPStan
    runs-on: ubuntu-latest

    services:
      database:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
          - "3306:3306"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: docker-compose up -d --build

      - name: Install dependencies
        run: docker-compose exec -T php composer install --no-interaction --prefer-dist

      - name: Run PHPStan
        run: docker-compose exec -T php vendor/bin/phpstan analyse -l max -c phpstan.neon src
