name: PHPStan Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  phpstan:
    name: Run PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose (if missing)
        run: |
          if ! command -v docker-compose &> /dev/null; then
            echo "Installing Docker Compose..."
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi
          docker-compose version

      - name: Start Docker services
        run: docker-compose up -d --build

      - name: Show running containers (debug)
        run: docker ps -a

      - name: Wait for services to be ready
        run: sleep 10

      - name: Install dependencies
        run: docker-compose exec -T php composer install --no-interaction --prefer-dist

      - name: Run PHPStan
        run: docker-compose exec -T php ./vendor/bin/phpstan analyse -l max -c phpstan.neon src

      - name: Show logs if failure
        if: failure()
        run: docker-compose logs
